### ISSUE TITLE
Removal of embedded snippet through "click-action" not being registered.

### ISSUE THREAD

**Issue by cecenz** [springload/wagtailembedder#5]
Wagtails Richtext editor doesn't register when an embedded snippet get's removed through clicking the "remove" icon in the top right corner.

Any actively issues key stroke in the affected field after removing the snippet fixes the issue. This points to the embedded snippet not correctly updating the editors "something has changed" process.

**Comment by loicteixeira** [comment]
The same behaviour happens with Wagtail native embed. An issue has been filled torchbox/wagtail#2637.

**Comment by loicteixeira** [comment]
A fix has been [merged into the 1.5.x branch](https://github.com/torchbox/wagtail/pull/2656#issuecomment-223614560) and should fix this issue.
